<table align="center" width=100%>
    <tr>
        <td width="15%">
            <img src="homework.png">
        </td>
        <td>
            <div align="center">
                <font color="#21618C" size=8px>
                    <b> TakeHome <br> (Session 3) </b>
                </font>
            </div>
        </td>
    </tr>
</table>

### Let's begin with some hands-on practice exercises

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>1. Create an array of integers from 20 to 2 with a step of -2
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

In [ ]:
import numpy as np
array = np.arange(20, 2, -2) 
array

array([20, 18, 16, 14, 12, 10,  8,  6,  4])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>2. Find the minimum value along with the row
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

#### Create a 2D Numpy array from list of lists
arr2D = np.array([[110, 102, 183],
                     [140, 175, 106],
                     [170, 195, 117],
                     [192, 140, 195]])

In [ ]:
arr2D = np.array([[110, 102, 183],
                     [140, 175, 106],
                     [170, 195, 117],
                     [192, 140, 195]])
min_value = np.amin(arr2D, axis=1)
                                                      
print('min value of every row: ', min_value)

min value of every row:  [102 106 117 140]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>3. Replace all odd numbers in array with -2
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below**<br>
arr = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])

In [ ]:
arr = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])
arr[arr % 2 == 1] = -2
arr

array([ 0, -2, 42, -2, 34, -2, 26, -2, 38, 94, -2, 78, 76])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>4. Replace all odd numbers in arr with -2 without changing original array
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below**<br>
arr = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])

In [ ]:
arr = np.array([0, 31, 42, 43, 34, 45, 26, 27, 38, 94, 65, 78, 76])
out = np.where(arr % 2 == 1, -2, arr)
print(arr)
print(out)

[ 0 31 42 43 34 45 26 27 38 94 65 78 76]
[ 0 -2 42 -2 34 -2 26 -2 38 94 -2 78 76]


<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>5. Stack two arrays vertically
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>
array1 = np.arange(10).reshape(2,-1)<br>
array2 = np.repeat(1, 10).reshape(2,-1)

In [ ]:
array1 = np.arange(10).reshape(2,-1)
array2 = np.repeat(1, 10).reshape(2,-1)

In [ ]:
np.concatenate([array1, array2], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.vstack([array1, array2])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>6. Get commom elements between two arrays
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>
array1 = np.array([11,12,13,22,23,44,43,24,45,36])<br>
array2 = np.array([17,22,13,22,47,34,39,44,29,28])

In [ ]:
array1 = np.array([11,12,13,22,23,44,43,24,45,36])
array2 = np.array([17,22,13,22,47,34,39,44,29,28])
np.intersect1d(array1,array2)

array([13, 22, 44])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>7. From array1 remove all items present in array2
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>
array1 = np.array([1,2,3,4,5])<br>
array2 = np.array([5,6,7,8,9])

In [ ]:
array1 = np.array([1,2,3,4,5])
array2 = np.array([5,6,7,8,9])
np.setdiff1d(array1,array2)

array([1, 2, 3, 4])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>8. Get the positions where elements of two array match
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>
array1 = np.array([1,2,3,2,3,4,3,4,5,6])<br>
array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [ ]:
array1 = np.array([1,2,3,2,3,4,3,4,5,6])
array2 = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(array1==array2)

(array([1, 3, 5, 7], dtype=int64),)

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>9. Reverse the columns of a 2D array
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>
array1 = np.arange(9).reshape(3,3)<br>

In [ ]:
array1 = np.arange(9).reshape(3,3)
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
array1[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

<table align="left">
    <tr>
        <td width="6%">
            <img src="question_icon.png">
        </td>
        <td>
            <div align="left", style="font-size:120%">
                <font color="#21618C">
                    <b>10. Swap rows 1 and 2 in the given array
</b>
                </font>
            </div>
        </td>
    </tr>
</table>

**Use the array given below:**<br>
array1 = np.arange(9).reshape(3,3)<br>

In [ ]:
# given array
array1 = np.arange(9).reshape(3,3)
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# modified array
array1[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])